#!/bin/sh /etc/rc.common
START=99 
STOP=99

start()  {
    echo "tuyaapp Start" >> /dev/ttyS0
	user_iot &
}

stop() {
	echo "tuyaapp stop" >> /dev/ttyS0
	killall user_iot
}

restart() {
	stop
	sleep 1
	start
}